import Users from "../dao/Users.dao.js";
import CustomerPaymentMethods from "../dao/CustomerPaymentMethods.dao.js";
import SupplierPaymentMethods from "../dao/SupplierPaymentMethods.dao.js";
import Customers from "../dao/Customers.dao.js";
import Suppliers from "../dao/Suppliers.dao.js";
import GeneralParameters from "../dao/GeneralParameters.dao.js";
import quotations from "../dao/Quotations.dao.js";
import Products from "../dao/Products.dao.js";
import Processes from "../dao/Processes.dao.js";
import UsersActions from "../dao/UsersActions.dao.js";
import Jobs from "../dao/Jobs.dao.js";
import JobProducts from "../dao/JobProducts.dao.js";
import JobProcesses from "../dao/JobProcesses.dao.js";
import JobsActions from "../dao/JobsActions.dao.js";
import Messages from "../dao/Messages.dao.js";

import UserRepository from "../repository/UserRepository.js";
import CustomerPaymentMethodRepository from "../repository/CustomerPaymentMethodRepository.js";
import SupplierPaymentMethodRepository from "../repository/SupplierPaymentMethodRepository.js";
import CustomerRepository from "../repository/CustomerRepository.js";
import SupplierRepository from "../repository/SupplierRepository.js";
import GeneralParameterRepository from "../repository/GeneralParameterRepository.js";
import QuotationRepository from "../repository/QuotationRepository.js";
import ProductRepository from "../repository/ProductRepository.js";
import ProcessRepository from "../repository/ProcessRepository.js";
import UsersActionsRepository from "../repository/UsersActionsRepository.js";
import JobRepository from "../repository/JobRepository.js";
import JobProductRepository from "../repository/JobProductRepository.js";
import JobProcessRepository from "../repository/JobProcessRepository.js";
import JobActionsRepository from "../repository/JobActionRepository.js";
import MessagesRepository from "../repository/MessageRepository.js";

export const usersService = new UserRepository(new Users());
export const customerPaymentMethodService = new CustomerPaymentMethodRepository(new CustomerPaymentMethods());
export const supplierPaymentMethodService = new SupplierPaymentMethodRepository(new SupplierPaymentMethods());
export const customerService = new CustomerRepository(new Customers());
export const supplierService = new SupplierRepository(new Suppliers());
export const generalParameterService = new GeneralParameterRepository(new GeneralParameters());
export const quotationService = new QuotationRepository(new quotations());
export const productService = new ProductRepository(new Products());
export const processService = new ProcessRepository(new Processes());
export const usersActionsService = new UsersActionsRepository(new UsersActions());
export const jobService = new JobRepository(new Jobs());
export const jobProductService = new JobProductRepository(new JobProducts());
export const jobProcessService = new JobProcessRepository(new JobProcesses());
export const jobsActionsService = new JobActionsRepository(new JobsActions());
export const messagesService = new MessagesRepository(new Messages());
